# there's a bunch of metadata in here that might only really make sense in dbt cloud
# In the deployments I've been involved with I've found that there's no discernable value in setting these values.
# As such I set these parameters to generic values that line everything up in a given repo.
name: usage_example
version: 0.0.1
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'current'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models", "udfs", "udafs", "procedures"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros", "../macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models: {}

tests: {}

flags:
  send_anonymous_usage_stats: false
  use_colors: true
